"""target position

Revision ID: 3be90abcb43d
Revises: c8d0bf5c1d
Create Date: 2014-08-28 15:21:37.174000

"""

# revision identifiers, used by Alembic.
from scotty.models import GUID

revision = '3be90abcb43d'
down_revision = 'c8d0bf5c1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_target_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', GUID(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('company_type_id', sa.Integer(), nullable=True),
    sa.Column('minimum_salary', sa.Integer(), nullable=False),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['company_type_id'], [u'company_type.id'], ),
    sa.ForeignKeyConstraint(['level_id'], [u'skill_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_preferred_cities',
    sa.Column('candidate_id', GUID(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], )
    )
    op.create_table('candidate_language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', GUID(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('proficiency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['language_id'], [u'language.id'], ),
    sa.ForeignKeyConstraint(['proficiency_id'], [u'proficiency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_position_skills_table',
    sa.Column('target_position_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['target_position_id'], ['candidate_target_position.id'], )
    )
    op.create_table('target_position_role_table',
    sa.Column('target_position_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['target_position_id'], ['candidate_target_position.id'], )
    )
    op.add_column(u'candidate', sa.Column('available_date', sa.Date(), nullable=True))
    op.add_column(u'candidate', sa.Column('notice_period_measure', sa.String(length=1), server_default='w', nullable=False))
    op.add_column(u'candidate', sa.Column('notice_period_number', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'candidate', 'notice_period_number')
    op.drop_column(u'candidate', 'notice_period_measure')
    op.drop_column(u'candidate', 'available_date')
    op.drop_table('target_position_role_table')
    op.drop_table('target_position_skills_table')
    op.drop_table('candidate_language')
    op.drop_table('candidate_preferred_cities')
    op.drop_table('candidate_target_position')
    ### end Alembic commands ###
