"""initial lookup tables

Revision ID: 3cd552c574af
Revises: 14368f86a87b
Create Date: 2014-08-26 18:56:51.817000

"""

# revision identifiers, used by Alembic.
import os
from sqlalchemy.sql import table, column

revision = '3cd552c574af'
down_revision = '14368f86a87b'

from alembic import op
import sqlalchemy as sa


def bulk_insert_names(tablename, fname):
    base = os.path.dirname(os.path.realpath(__file__))
    file_location = os.path.normpath(os.path.join(base, '..', 'lookups', fname))
    with open(file_location, 'r') as names:
        t = table(tablename, column("name", sa.String))
        op.bulk_insert(t, [{"name": name} for name in names])


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('proficiency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skill_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('education_degree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso'),
    sa.UniqueConstraint('name')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], [u'country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'name')
    )
    ### end Alembic commands ###

    bulk_insert_names("title", 'titles.csv')
    bulk_insert_names("company_type", 'company_types.csv')
    bulk_insert_names("skill_level", "skill_level.csv")
    bulk_insert_names("skill", "skills.csv")
    bulk_insert_names("proficiency", "proficiency.csv")
    bulk_insert_names("language", "languages.csv")
    bulk_insert_names("education_degree", "education_degrees.csv")
    bulk_insert_names("role", "roles.csv")
    bulk_insert_names("job_title", "job_titles.csv")


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    op.drop_table('country')
    op.drop_table('title')
    op.drop_table('education_degree')
    op.drop_table('job_title')
    op.drop_table('skill_level')
    op.drop_table('company_type')
    op.drop_table('language')
    op.drop_table('skill')
    op.drop_table('proficiency')
    op.drop_table('role')
    ### end Alembic commands ###
