"""adding counter

Revision ID: 14368f86a87b
Revises: fad5f74ad1f
Create Date: 2014-08-25 22:02:04.573000

"""

# revision identifiers, used by Alembic.
revision = '14368f86a87b'
down_revision = 'fad5f74ad1f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import Integer, String


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('counter', sa.Integer(), nullable=True))
    p = table("models", column('name', String), column('counter', Integer))
    op.bulk_insert(p, [{'name': 'one', "counter": "0"}])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'counter')
    ### end Alembic commands ###
