"""offer

Revision ID: 1c0d55359623
Revises: 1b3bfaa82d89
Create Date: 2014-09-18 14:48:59.422000

"""

# revision identifiers, used by Alembic.
from scotty.models import GUID
from scotty.models.tools import csv_inserter

revision = '1c0d55359623'
down_revision = '1b3bfaa82d89'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejectionreason',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'))
    op.create_table('offer',
                    sa.Column('id', GUID(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('accepted', sa.DateTime(), nullable=True),
                    sa.Column('rejected', sa.DateTime(), nullable=True),
                    sa.Column('rejected_reason_id', sa.Integer(), nullable=True),
                    sa.Column('candidate_id', GUID(), nullable=False),
                    sa.Column('employer_id', GUID(), nullable=False),
                    sa.Column('location_id', sa.Integer(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('annual_salary', sa.Integer(), nullable=False),
                    sa.Column('interview_details', sa.Text(), nullable=True),
                    sa.Column('job_description', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
                    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
                    sa.ForeignKeyConstraint(['location_id'], [u'city.id'], ),
                    sa.ForeignKeyConstraint(['rejected_reason_id'], ['rejectionreason.id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('candidate_id', 'employer_id', 'annual_salary', 'location_id', name='_candidate_employer_offer_unique'))
    op.create_table('offer_benefit',
                    sa.Column('offer_id', GUID(), nullable=False),
                    sa.Column('benefit_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['benefit_id'], ['benefit.id'], ),
                    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
                    sa.PrimaryKeyConstraint('offer_id', 'benefit_id'))
    op.create_table('offer_skill',
                    sa.Column('offer_id', GUID(), nullable=False),
                    sa.Column('skill_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
                    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
                    sa.PrimaryKeyConstraint('offer_id', 'skill_id'))
    ### end Alembic commands ###

    bulk_insert_names = csv_inserter(__file__)
    bulk_insert_names("rejectionreason", 'rejectionreasons.csv')

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_skill')
    op.drop_table('offer_benefit')
    op.drop_table('offer')
    op.drop_table('rejectionreason')
    ### end Alembic commands ###
