"""candidate revert back to location



Revision ID: 43c53e5c33b1

Revises: 3e054601fee6

Create Date: 2014-10-16 13:24:01.517000



"""



# revision identifiers, used by Alembic.

revision = '43c53e5c33b1'

down_revision = '3e054601fee6'



from alembic import op

import sqlalchemy as sa





def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('location_id', sa.Integer(), nullable=True))
    op.drop_column('candidate', 'contact_city')
    op.drop_column('candidate', 'contact_country_iso')
    ### end Alembic commands ###




def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('contact_country_iso', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('candidate', sa.Column('contact_city', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('candidate', 'location_id')
    ### end Alembic commands ###

