"""base candidate

Revision ID: b316f28cef
Revises: 13b561ffb84f
Create Date: 2014-08-27 13:39:10.498000

"""

# revision identifiers, used by Alembic.
from scotty.models import GUID
from scotty.models.tools import csv_inserter

revision = 'b316f28cef'
down_revision = '13b561ffb84f'

from alembic import op
import sqlalchemy as sa


bulk_insert_names = csv_inserter(__file__)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('traffic_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('candidate',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=False),
    sa.Column('pwd', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=512), nullable=False),
    sa.Column('last_name', sa.String(length=512), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('pob', sa.String(length=512), nullable=True),
    sa.Column('picture_url', sa.String(length=1024), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.Column('residence_country_iso', sa.String(length=2), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('github_url', sa.String(length=1024), nullable=True),
    sa.Column('stackoverflow_url', sa.String(length=1024), nullable=True),
    sa.Column('traffic_source_id', sa.Integer(), nullable=True),
    sa.Column('contact_line1', sa.String(length=512), nullable=True),
    sa.Column('contact_line2', sa.String(length=512), nullable=True),
    sa.Column('contact_line3', sa.String(length=512), nullable=True),
    sa.Column('contact_zipcode', sa.String(length=20), nullable=True),
    sa.Column('contact_city_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('willing_to_travel', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contact_city_id'], [u'city.id'], ),
    sa.ForeignKeyConstraint(['residence_country_iso'], [u'country.iso'], ),
    sa.ForeignKeyConstraint(['status_id'], [u'candidate_status.id'], ),
    sa.ForeignKeyConstraint(['title_id'], [u'title.id'], ),
    sa.ForeignKeyConstraint(['traffic_source_id'], [u'traffic_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###
    bulk_insert_names("candidate_status", 'candidate_status.csv')

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate')
    op.drop_table('traffic_source')
    op.drop_table('candidate_status')
    ### end Alembic commands ###
