"""lower case city index

Revision ID: 13b561ffb84f
Revises: 9ddb2420d0d
Create Date: 2014-08-26 22:53:58.641000

"""

# revision identifiers, used by Alembic.
from sqlalchemy.sql import column

revision = '13b561ffb84f'
down_revision = '9ddb2420d0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE INDEX city_names_lower ON city (lower(name))")
    op.execute("CREATE INDEX country_names_lower ON country (lower(name))")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('country_names_lower', table_name='country')
    op.drop_index('city_names_lower', table_name='city')
    ### end Alembic commands ###
