"""invite-code-reference, admin comments



Revision ID: 40f6ffa812c6

Revises: 46cdb3225fc7

Create Date: 2014-10-21 18:37:47.386000



"""



# revision identifiers, used by Alembic.

revision = '40f6ffa812c6'

down_revision = '46cdb3225fc7'



from alembic import op

import sqlalchemy as sa





def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('admin_comment', sa.Text(), nullable=True))
    op.add_column('candidate', sa.Column('invite_code_id', sa.Integer(), nullable=True))
    op.add_column('employer', sa.Column('admin_comment', sa.Text(), nullable=True))
    ### end Alembic commands ###



def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employer', 'admin_comment')
    op.drop_column('candidate', 'invite_code_id')
    op.drop_column('candidate', 'admin_comment')
    ### end Alembic commands ###

