"""drop target position columns



Revision ID: 46a272d780af

Revises: 4de957131065

Create Date: 2014-10-10 17:33:28.430000



"""



# revision identifiers, used by Alembic.

revision = '46a272d780af'

down_revision = '4de957131065'



from alembic import op

import sqlalchemy as sa





def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_position_company_type')
    op.drop_column('target_position', 'relocate')
    op.drop_column('target_position', 'travel_willingness_id')
    ### end Alembic commands ###





def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_position', sa.Column('travel_willingness_id', sa.INTEGER(), server_default='1', autoincrement=False, nullable=False))
    op.add_column('target_position', sa.Column('relocate', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('target_position_company_type',
                    sa.Column('target_position_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('company_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['company_type_id'], [u'company_type.id'], name=u'target_position_company_type_company_type_id_fkey'),
                    sa.ForeignKeyConstraint(['target_position_id'], [u'target_position.id'], name=u'target_position_company_type_target_position_id_fkey'),
                    sa.PrimaryKeyConstraint('target_position_id', 'company_type_id', name=u'target_position_company_type_pkey')
    )
    ### end Alembic commands ###

