"""update management role name

Revision ID: 8daffc86869
Revises: 545a229bf35a
Create Date: 2014-12-02 15:23:01.822119

"""

# revision identifiers, used by Alembic.
revision = '8daffc86869'
down_revision = '545a229bf35a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("""update role set name='CTO/CIO (IT Management)' where name='Engineering Management';""")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("""update role set name='Engineering Management' where name='CTO/CIO (IT Management)';""")
    ### end Alembic commands ###
