"""candidate skills

Revision ID: 1413d97c9b30
Revises: b316f28cef
Create Date: 2014-08-27 13:52:41.710000

"""

# revision identifiers, used by Alembic.
from scotty.models import GUID

revision = '1413d97c9b30'
down_revision = 'b316f28cef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', GUID(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], [u'skill.id'], ),
    sa.ForeignKeyConstraint(['skill_level_id'], [u'skill_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_skill')
    ### end Alembic commands ###
