"""nullables on work experience



Revision ID: 5018de3ec549

Revises: 1dc0099a963e

Create Date: 2014-10-15 19:18:50.313000



"""



# revision identifiers, used by Alembic.

revision = '5018de3ec549'

down_revision = '1dc0099a963e'



from alembic import op

import sqlalchemy as sa





def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_experience', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('work_experience', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('work_experience', 'summary',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###



def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_experience', 'summary',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('work_experience', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('work_experience', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###

