"""offerflow state changes

Revision ID: 4f5891e25400
Revises: 397b66debe45
Create Date: 2014-10-02 17:57:43.693000

"""

# revision identifiers, used by Alembic.
from scotty.models.tools import csv_inserter

revision = '4f5891e25400'
down_revision = '397b66debe45'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawalreason',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'))

    bulk_insert_names = csv_inserter(__file__)
    bulk_insert_names("withdrawalreason", 'withdrawal_reasons.csv')
    op.add_column('offer', sa.Column('contract_negotiation', sa.DateTime(), nullable=True))
    op.add_column('offer', sa.Column('job_start_date', sa.DateTime(), nullable=True))
    op.add_column('offer', sa.Column('job_start_salary', sa.Integer(), nullable=True))
    op.add_column('offer', sa.Column('withdrawal_reason_id', sa.Integer(), nullable=True))
    op.add_column('offer', sa.Column('withdrawal_text', sa.Text(), nullable=True))
    op.add_column('offer', sa.Column('withdrawn', sa.DateTime(), nullable=True))
    op.drop_column('offer', 'job_started')
    op.drop_column('offer', 'contract_received')
    op.drop_column('offer', 'contract_sent')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('contract_sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('offer', sa.Column('contract_received', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('offer', sa.Column('job_started', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('offer', 'withdrawn')
    op.drop_column('offer', 'withdrawal_text')
    op.drop_column('offer', 'withdrawal_reason_id')
    op.drop_column('offer', 'job_start_salary')
    op.drop_column('offer', 'job_start_date')
    op.drop_column('offer', 'contract_negotiation')
    op.drop_table('withdrawalreason')
    ### end Alembic commands ###
