"""anonymous

Revision ID: 225a3e8e3ce9
Revises: 14cea77f6cc6
Create Date: 2014-11-13 12:21:50.370124

"""

# revision identifiers, used by Alembic.
revision = '225a3e8e3ce9'
down_revision = '14cea77f6cc6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('anonymous', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'anonymous')
    ### end Alembic commands ###
