"""invitecodes



Revision ID: 6899bb21e06

Revises: 3d172126fbd7

Create Date: 2014-10-16 21:53:34.956000



"""



# revision identifiers, used by Alembic.

revision = '6899bb21e06'

down_revision = '3d172126fbd7'



from alembic import op

import sqlalchemy as sa





def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_code',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('code', sa.String(length=64), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
    )
    op.execute('create sequence offer_reference_seq start 7021')
    op.execute("alter table offer add column reference integer default nextval('offer_reference_seq') not null")
    op.create_unique_constraint(None, 'offer', ['reference'])
    ### end Alembic commands ###





def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite_code')
    op.execute('alter table offer drop column reference cascade;')
    op.execute('drop sequence offer_reference_seq;')
    ### end Alembic commands ###

