"""work experience skills

Revision ID: 441f5073cc28
Revises: 2f46dd308cb0
Create Date: 2014-09-09 10:49:19.404000

"""

# revision identifiers, used by Alembic.
from scotty.models import GUID

revision = '441f5073cc28'
down_revision = '2f46dd308cb0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_experience_skill',
                    sa.Column('work_experience_id', sa.Integer(), nullable=False),
                    sa.Column('skill_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
                    sa.ForeignKeyConstraint(['work_experience_id'], ['work_experience.id'], ),
                    sa.PrimaryKeyConstraint('work_experience_id', 'skill_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experience_skill')
    ### end Alembic commands ###
