"""add otherbenefits col

Revision ID: 28f72b5225a3
Revises: 225a3e8e3ce9
Create Date: 2014-11-27 16:21:07.645100

"""

# revision identifiers, used by Alembic.
revision = '28f72b5225a3'
down_revision = '225a3e8e3ce9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employer', sa.Column('other_benefits', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employer', 'other_benefits')
    ### end Alembic commands ###
