"""featured cols



Revision ID: 4de957131065

Revises: 4f5891e25400

Create Date: 2014-10-08 12:04:31.156000



"""



# revision identifiers, used by Alembic.

revision = '4de957131065'

down_revision = '4f5891e25400'



from alembic import op

import sqlalchemy as sa


def set_featured_order(items, table_name):
    """
    merge inert update & set order
    """
    op.execute(sa.text("""insert into %(table)s (name) select a.name from
                          (select '%(head)s' as name %(tail)s) as a
                          left outer join %(table)s s on lower(s.name) = lower(a.name)
                          WHERE s.id is null""" % {'table': table_name,
                                                   'head': items[0],
                                                   'tail': '  '.join(["UNION SELECT '%s'" % item for item in items[1:]])}
    ))

    for i, item in enumerate(items):
        op.execute(sa.text("update %s set featured_order=%s where lower(name) = lower('%s')" % (table_name, i+1, item)))


def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('featured_order', sa.Integer(), nullable=True))
    op.add_column('language', sa.Column('featured_order', sa.Integer(), nullable=True))
    op.add_column('role', sa.Column('featured_order', sa.Integer(), nullable=True))
    op.add_column('skill', sa.Column('featured_order', sa.Integer(), nullable=True))
    op.add_column('candidate', sa.Column('eu_work_visa', sa.Boolean(), nullable=True))
    op.add_column('candidate', sa.Column('cv_upload_url', sa.String(length=1024), nullable=True))

    skills = ['Java', '.Net', 'PHP', 'Python', 'Ruby', 'C/C++', 'JavaScript', 'HTML/CSS', 'Android', 'iOS', 'Linux', 'Salesforce', 'SAP']
    set_featured_order(skills, 'skill')

    roles = [
        'Software Development',
        'Product or Project Management',
        'Engineering Management',
        'Quality Assurance',
        'UX/UI design',
        'System Administration',
        'Data Scientist',
        'Technical Consultant or Sales Support',
        ]
    set_featured_order(roles, 'role')

    languages = ['German', 'English']
    set_featured_order(languages, 'language')

    cities = [('Berlin', 'DE'),
              ('Hamburg', 'DE'),
              ('Munich', 'DE')]
    for i, (city, country_iso) in enumerate(cities):
        op.execute(sa.text("update city set featured_order=%s where lower(name) = lower('%s') and country_iso = '%s'" %
                           (i+1, city, country_iso)))
        ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'featured_order')
    op.drop_column('role', 'featured_order')
    op.drop_column('language', 'featured_order')
    op.drop_column('city', 'featured_order')
    op.drop_column('candidate', 'eu_work_visa')
    op.drop_column('candidate', 'cv_upload_url')
    ### end Alembic commands ###

