"""Base Lookups

Revision ID: 113bcbd6094a
Revises: None
Create Date: 2014-08-29 19:03:23.101000

"""

# revision identifiers, used by Alembic.
from scotty.models.tools import csv_inserter

revision = '113bcbd6094a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('iso', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('iso'),
    sa.UniqueConstraint('name')
    )
    op.create_table('institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('education_degree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('seniority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skill_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('proficiency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('traffic_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_iso', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['country_iso'], [u'country.iso'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_iso', 'name', name='city_name_country_unique')
    )
    ### end Alembic commands ###

    bulk_insert_names = csv_inserter(__file__)
    bulk_insert_names("title", 'titles.csv')
    bulk_insert_names("company_type", 'company_types.csv')
    bulk_insert_names("skill_level", "skill_level.csv")
    bulk_insert_names("skill", "skills.csv")
    bulk_insert_names("proficiency", "proficiency.csv")
    bulk_insert_names("language", "languages.csv")
    bulk_insert_names("education_degree", "education_degrees.csv")
    bulk_insert_names("role", "roles.csv")
    bulk_insert_names("job_title", "job_titles.csv")
    bulk_insert_names("country", "countries.csv", ['name', 'iso'])
    bulk_insert_names("city", "cities_15000.csv", ['name', 'latitude', 'longitude', 'country_iso'])

    op.execute("CREATE INDEX city_names_lower ON city (lower(name))")
    op.execute("CREATE UNIQUE INDEX country_names_lower ON country (lower(name))")

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    op.drop_table('role')
    op.drop_table('traffic_source')
    op.drop_table('proficiency')
    op.drop_table('title')
    op.drop_table('skill_level')
    op.drop_table('language')
    op.drop_table('company_type')
    op.drop_table('company')
    op.drop_table('job_title')
    op.drop_table('skill')
    op.drop_table('seniority')
    op.drop_table('education_degree')
    op.drop_table('institution')
    op.drop_table('country')
    ### end Alembic commands ###
