"""cms content



Revision ID: 36ec1e177615

Revises: 40f6ffa812c6

Create Date: 2014-10-28 12:57:55.605000



"""



# revision identifiers, used by Alembic.

revision = '36ec1e177615'

down_revision = '40f6ffa812c6'



from alembic import op

import sqlalchemy as sa



def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_content',
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('value', sa.String(length=4000), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    ### end Alembic commands ###


def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cms_content')
    ### end Alembic commands ###

