"""initials

Revision ID: fad5f74ad1f
Revises: None
Create Date: 2014-08-25 21:23:30.683000

"""

# revision identifiers, used by Alembic.
revision = 'fad5f74ad1f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('my_index', 'models', ['name'], unique=True, mysql_length=255)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('my_index', table_name='models')
    op.drop_table('models')
    ### end Alembic commands ###
