"""offer other benefits

Revision ID: 4ea9462296b1
Revises: 314b2abd6200
Create Date: 2014-12-13 13:09:04.965979

"""

# revision identifiers, used by Alembic.
revision = '4ea9462296b1'
down_revision = '314b2abd6200'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('other_benefits', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'other_benefits')
    ### end Alembic commands ###
