"""candidate work experience

Revision ID: c8d0bf5c1d
Revises: 36032acdd96f
Create Date: 2014-08-27 20:13:57.510000

"""

# revision identifiers, used by Alembic.
from scotty.models import GUID
from scotty.models.tools import csv_inserter

revision = 'c8d0bf5c1d'
down_revision = '36032acdd96f'

from alembic import op
import sqlalchemy as sa


bulk_insert_names = csv_inserter(__file__)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('candidate_work_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', GUID(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['city_id'], [u'city.id'], ),
    sa.ForeignKeyConstraint(['company_id'], [u'company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_work_experience_role',
    sa.Column('work_experience_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['work_experience_id'], ['candidate_work_experience.id'], )
    )
    op.create_table('candidate_work_experience_job_title',
    sa.Column('work_experience_id', sa.Integer(), nullable=True),
    sa.Column('job_title_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_title.id'], ),
    sa.ForeignKeyConstraint(['work_experience_id'], ['candidate_work_experience.id'], )
    )
    op.alter_column(u'candidate_education', 'end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column(u'candidate_education', 'start',
               existing_type=sa.DATE(),
               nullable=False)
    ### end Alembic commands ###

    bulk_insert_names("company", 'companies.csv')


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'candidate_education', 'start',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column(u'candidate_education', 'end',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_table('candidate_work_experience_job_title')
    op.drop_table('candidate_work_experience_role')
    op.drop_table('candidate_work_experience')
    op.drop_table('company')
    ### end Alembic commands ###
