"""Target position not required fields anymore

Revision ID: 35f3d4af61d4
Revises: 486708e1255c
Create Date: 2015-03-31 11:27:08.947399

"""

# revision identifiers, used by Alembic.
revision = '35f3d4af61d4'
down_revision = '486708e1255c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_position', 'minimum_salary',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('target_position', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('work_experience', 'start',
               existing_type=sa.DATE(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_experience', 'start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('target_position', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('target_position', 'minimum_salary',
               existing_type=sa.BIGINT(),
               nullable=False)
    ### end Alembic commands ###
