"""last_sent date



Revision ID: 49870407fd90

Revises: 34599ac42b52

Create Date: 2015-03-04 15:39:27.637000



"""



# revision identifiers, used by Alembic.

revision = '49870407fd90'

down_revision = '34599ac42b52'



from alembic import op

import sqlalchemy as sa





def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_candidates', sa.Column('last_sent', sa.DateTime(), nullable=True))
    ### end Alembic commands ###





def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggested_candidates', 'last_sent')
    ### end Alembic commands ###

