"""saved searches for employer

Revision ID: 1ed3688463e4
Revises: 50dbf2940497
Create Date: 2015-04-30 10:58:19.089788

"""

# revision identifiers, used by Alembic.
from scotty.models import GUID

revision = '1ed3688463e4'
down_revision = '50dbf2940497'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer_savedsearch',
                    sa.Column('id', GUID(), nullable=False),
                    sa.Column('employer_id', GUID(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('name', sa.String(length=512), nullable=True),
                    sa.Column('terms', postgresql.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employer_savedsearch')
    ### end Alembic commands ###
