"""further work experioence, education steps

Revision ID: d947904fa9a
Revises: 35f3d4af61d4
Create Date: 2015-04-08 12:50:55.289722

"""

# revision identifiers, used by Alembic.
revision = 'd947904fa9a'
down_revision = '35f3d4af61d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('no_further_edu', sa.DateTime(), nullable=True))
    op.add_column('candidate', sa.Column('no_further_wxp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'no_further_wxp')
    op.drop_column('candidate', 'no_further_edu')
    ### end Alembic commands ###
