"""add blog_url

Revision ID: 5ad13ff72d79
Revises: 3433ab917945
Create Date: 2015-01-01 15:44:27.994382

"""

# revision identifiers, used by Alembic.
revision = '5ad13ff72d79'
down_revision = '3433ab917945'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('blog_url', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'blog_url')
    ### end Alembic commands ###
