"""make target position primary

Revision ID: 649031fee6b
Revises: 11fe1e4b96a1
Create Date: 2015-01-27 15:39:44.115250

"""

# revision identifiers, used by Alembic.
revision = '649031fee6b'
down_revision = '11fe1e4b96a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.execute("insert into target_position (candidate_id, created, role_id, minimum_salary) "
               "select id, NOW(), (select min(id) from role), 40000 from candidate where id not in (select distinct candidate_id from target_position);")

    op.execute("ALTER TABLE target_position drop constraint target_position_pkey cascade;")
    op.execute("ALTER TABLE target_position drop constraint target_position_candidate_id_fkey;")
    op.execute("ALTER TABLE target_position ADD PRIMARY KEY (candidate_id);")

    op.execute("ALTER TABLE target_position_skills add column target_position_candidate_id UUID;")

    op.execute("UPDATE target_position_skills set target_position_candidate_id = tp.candidate_id "
               "from target_position tp where target_position_id = tp.id;")

    op.execute("ALTER TABLE target_position_skills drop column target_position_id;")
    op.execute("ALTER TABLE target_position_skills ADD PRIMARY KEY (target_position_candidate_id, skill_id)")
    op.execute("ALTER TABLE target_position_skills ADD CONSTRAINT target_position_skills_target_position_id_fkey "
               "FOREIGN KEY (target_position_candidate_id) REFERENCES target_position (candidate_id);")

    op.execute('ALTER TABLE target_position drop column id;')

    op.execute("ALTER TABLE candidate ADD CONSTRAINT target_position_candidate_id_fkey "
               "FOREIGN KEY (id) REFERENCES target_position (candidate_id);")

    op.execute("ALTER TABLE candidate_preferred_location drop constraint candidate_preferred_location_candidate_id_fkey;")
    op.execute("ALTER TABLE candidate_preferred_location RENAME COLUMN candidate_id to target_position_candidate_id;")
    op.execute("ALTER TABLE candidate_preferred_location ADD CONSTRAINT candidate_preferred_location_tp_candidate_id_fkey "
               "FOREIGN KEY (target_position_candidate_id) REFERENCES target_position (candidate_id);")


    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.execute("""
    delete from candidate_preferred_location where target_position_candidate_id not in (select id from candidate);
    delete from target_position_skills where target_position_candidate_id not in (select id from candidate);
    delete from target_position where candidate_id not in (select id from candidate);
    """)

    op.execute("ALTER TABLE target_position add column id SERIAL not null")

    op.execute("ALTER TABLE target_position drop constraint target_position_pkey CASCADE;")
    op.execute("ALTER TABLE target_position ADD CONSTRAINT target_position_candidate_id_fkey "
               "FOREIGN KEY (candidate_id) REFERENCES candidate (id);")
    op.execute("ALTER TABLE target_position ADD PRIMARY KEY (id);")


    op.execute("ALTER TABLE target_position_skills add column target_position_id INTEGER;")
    op.execute("UPDATE target_position_skills set target_position_id = tp.id "
               "from target_position tp where target_position_candidate_id = tp.candidate_id;")

    op.execute("ALTER TABLE target_position_skills drop constraint target_position_skills_pkey;")
    op.execute("ALTER TABLE target_position_skills drop column target_position_candidate_id;")

    op.execute("ALTER TABLE target_position_skills ADD PRIMARY KEY (target_position_id, skill_id)")

    op.execute("ALTER TABLE target_position_skills ADD CONSTRAINT target_position_skills_target_position_id_fkey "
               "FOREIGN KEY (target_position_id) REFERENCES target_position (id);")

    op.execute("ALTER TABLE candidate_preferred_location drop constraint candidate_preferred_location_tp_candidate_id_fkey;")
    op.execute("ALTER TABLE candidate_preferred_location RENAME COLUMN target_position_candidate_id to candidate_id;")
    op.execute("ALTER TABLE candidate_preferred_location ADD CONSTRAINT  candidate_preferred_location_candidate_id_fkey"
               "FOREIGN KEY (candidate_id) REFERENCES candidate (id);")


    op.execute(sa.text("DROP FUNCTION IF EXISTS candidate_search(skills varchar[], p_city_id int);"))
    op.execute(sa.text("""
        create or replace FUNCTION candidate_search(skills varchar[], p_city_id int, p_status_id int) RETURNS table (candidate_id uuid, matched_tags varchar[])
        AS $$

        DECLARE
                city_geog geography;
                l_country_iso varchar;
        BEGIN

        city_geog = st_GeogFromText('SRID=4326;POINT(' || longitude || ' ' || latitude || ')')
        from city
        where id = p_city_id;

        l_country_iso = country_iso
        from city
        where id = p_city_id;

        return query
        select c.id as id,
        array_agg(distinct s.name) as matched_tags
        from candidate c
        join candidate_skill cs
            on c.id = cs.candidate_id
        join skill s
            on s.id = cs.skill_id
        join candidate_preferred_location cpl
            on cpl.candidate_id = c.id
        left join country co
            on cpl.country_iso = co.iso
        left join city ci
            on ci.id = cpl.city_id
        where s.name = any(skills)
        and (status_id = p_status_id or p_status_id is null)
        and (ST_Distance(city_geog, ci.geog) < 50000 or p_city_id is null)
        or co.iso = l_country_iso
        group by c.id;
        END;
        $$ LANGUAGE plpgsql;
    """))


    op.execute("DROP FUNCTION IF EXISTS cn_candidate_search(term varchar(255), employer_id uuid);")
    op.execute("DROP VIEW IF EXISTS public.v_candidate_search;")
    op.execute("DROP VIEW IF EXISTS public.v_candidate_current_employers;")

    op.execute("""
        CREATE VIEW public.v_candidate_current_employers
        AS
        select candidate_id, e.id employer_id
                from work_experience we
                join company c
                   on c.id = we.company_id
                join employer e
                    on lower(e.company_name) = lower(c.name)
                where we.end is null;
    """)

    op.execute("""
        CREATE VIEW public.v_candidate_search
        AS

        SELECT
            c.id,
            cs.name as status,
            to_tsvector(cast(c.id AS VARCHAR(34)) || ', ' ||
            c.first_name || ' ' || c.last_name || ', ' || x.skills || ', ' || y.countries
            || ', ' || y.cities) AS search_index,
            to_tsvector(cast(c.id AS VARCHAR(34)) || ', ' ||
            case when c.anonymous = true then '' else c.first_name || ' ' || c.last_name end
             || ', ' || x.skills || ', ' || y.countries
            || ', ' || y.cities) AS anon_search_index,
            o.employer_ids,
            ce.current_employer_ids
              FROM candidate c
            JOIN target_position tp
              ON c.id = tp.candidate_id
            JOIN role r
              ON r.id = tp.role_id
            JOIN candidatestatus cs
              ON cs.id = c.status_id
            JOIN (
                   SELECT
                 candidate_id,
                 cast(array_agg(s.name) AS VARCHAR(400)) skills
                   FROM candidate_skill cskill
                 join skill s on s.id = cskill.skill_id
                   GROUP BY candidate_id
                 ) x
              ON x.candidate_id = c.id
            JOIN (
                   SELECT
                 cpl.candidate_id,
                 cast(array_agg(co.name) AS VARCHAR(400)) AS countries,
                 cast(array_agg(ci.name) AS VARCHAR(400)) AS cities
                   FROM candidate_preferred_location cpl
                 LEFT JOIN country co
                   ON co.iso = cpl.country_iso
                 LEFT JOIN city ci
                   ON ci.id = cpl.city_id
                   GROUP BY cpl.candidate_id
                 ) y
              ON y.candidate_id = c.id
            left join (
                select candidate_id, array_agg(employer_id) employer_ids
                from offer
                where accepted is not null
                group by candidate_id
                )o
                on o.candidate_id = c.id
            left join
            (
                select candidate_id, array_agg(e.employer_id) current_employer_ids
                from v_candidate_current_employers e
                group by candidate_id
            )ce
                on ce.candidate_id = c.id
            where cs.name = 'active';


        CREATE OR REPLACE FUNCTION cn_candidate_search(term varchar(255), employer_id uuid)
          RETURNS table (candidate_id uuid, status varchar(32)) AS $$
            BEGIN
            if employer_id is not null then
                    RETURN QUERY
                    SELECT distinct cs.id, cs.status
                    from public.v_candidate_search cs
                    where (current_employer_ids is null or employer_id != any(current_employer_ids))
                    and (anon_search_index @@ to_tsquery(term)
                    or (employer_id = any(employer_ids) and search_index @@ to_tsquery(term)));
                else
                    RETURN QUERY
                    SELECT distinct cs.id, cs.status
                    from public.v_candidate_search cs
                    where anon_search_index @@ to_tsquery(term);
            end if;
           END;
           $$
          LANGUAGE plpgsql VOLATILE
          COST 100;
    """)
    ### end Alembic commands ###

    ### end Alembic commands ###
