"""usergenerated locations

Revision ID: 51c3c89a18d6
Revises: 3b7e4541229
Create Date: 2015-05-29 22:05:53.094333

"""

# revision identifiers, used by Alembic.
revision = '51c3c89a18d6'
down_revision = '3b7e4541229'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('user_created', sa.Boolean(), nullable=False, server_default='0'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'user_created')
    ### end Alembic commands ###
