"""hand picked

Revision ID: 34599ac42b52
Revises: 314fe6e18e84
Create Date: 2015-02-27 12:49:00.244067

"""

# revision identifiers, used by Alembic.
from scotty.models import GUID

revision = '34599ac42b52'
down_revision = '314fe6e18e84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggested_candidates',
                    sa.Column('employer_id', GUID(), nullable=False),
                    sa.Column('candidate_id', GUID(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('employer_not_interested', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
                    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
                    sa.PrimaryKeyConstraint('employer_id', 'candidate_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggested_candidates')
    ### end Alembic commands ###
