"""IT Insights

Revision ID: 15f4de12bc2d
Revises: 426c68fc9c8f
Create Date: 2015-02-12 18:02:03.729171

"""

# revision identifiers, used by Alembic.
revision = '15f4de12bc2d'
down_revision = '426c68fc9c8f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employer', sa.Column('cto_blog', sa.Text(), nullable=True))
    op.add_column('employer', sa.Column('cto_twitter', sa.Text(), nullable=True))
    op.add_column('employer', sa.Column('dev_methodology', sa.Text(), nullable=True))
    op.add_column('employer', sa.Column('tech_team_office', sa.Text(), nullable=True))
    op.add_column('employer', sa.Column('working_env', sa.Text(), nullable=True))
    op.add_column('employer', sa.Column('video_script', sa.Text(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employer', 'working_env')
    op.drop_column('employer', 'tech_team_office')
    op.drop_column('employer', 'dev_methodology')
    op.drop_column('employer', 'cto_twitter')
    op.drop_column('employer', 'cto_blog')
    op.drop_column('employer', 'video_script')
    ### end Alembic commands ###
