"""featured degrees

Revision ID: 17714a89e316
Revises: 49870407fd90
Create Date: 2015-03-13 10:50:29.565789

"""

# revision identifiers, used by Alembic.
revision = '17714a89e316'
down_revision = '49870407fd90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('degree', sa.Column('featured_order', sa.Integer(), nullable=True))

    values = ['PhD', 'Master', 'Bachelor', 'Vocational training']
    for i, v in enumerate(values):
        op.execute("update degree set featured_order=%s where name ='%s'" % (i, v))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('degree', 'featured_order')
    ### end Alembic commands ###
