"""employer pictures

Revision ID: 426c68fc9c8f
Revises: 21dc9a40fc41
Create Date: 2015-02-09 17:24:12.615202

"""

# revision identifiers, used by Alembic.
from scotty.models import GUID

revision = '426c68fc9c8f'
down_revision = '21dc9a40fc41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer_picture',
                    sa.Column('id', GUID(), nullable=False),
                    sa.Column('employer_id', GUID(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('description', sa.String(length=1024), nullable=True),
                    sa.Column('url', sa.String(length=1024), nullable=False),
                    sa.Column('position', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employer_picture')
    ### end Alembic commands ###
