"""last_active

Revision ID: 28405ee14b74
Revises: 557324a962d5
Create Date: 2015-02-25 12:46:08.796587

"""

# revision identifiers, used by Alembic.
revision = '28405ee14b74'
down_revision = '557324a962d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('last_active', sa.DateTime()))
    op.add_column('candidate', sa.Column('last_login', sa.DateTime()))
    op.add_column('employer', sa.Column('last_active', sa.DateTime()))
    op.add_column('employer', sa.Column('last_login', sa.DateTime()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employer', 'last_login')
    op.drop_column('employer', 'last_active')
    op.drop_column('candidate', 'last_login')
    op.drop_column('candidate', 'last_active')
    ### end Alembic commands ###
