"""add language columns

Revision ID: 21dc9a40fc41
Revises: 4e2e78fbcf75
Create Date: 2015-02-09 16:23:10.666408

"""

# revision identifiers, used by Alembic.
revision = '21dc9a40fc41'
down_revision = '4e2e78fbcf75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.execute("insert into locale values (1, 'en'), (2, 'de')")
    op.add_column('candidate', sa.Column('locale_id', sa.Integer(), server_default='1', nullable=False))
    op.add_column('employer', sa.Column('locale_id', sa.Integer(), server_default='1', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employer', 'locale_id')
    op.drop_column('candidate', 'locale_id')
    op.drop_table('locale')
    ### end Alembic commands ###
