"""moving signup before target position

Revision ID: 486708e1255c
Revises: 17714a89e316
Create Date: 2015-03-19 11:37:12.480123

"""

# revision identifiers, used by Alembic.
revision = '486708e1255c'
down_revision = '17714a89e316'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("delete from target_position_skills where target_position_candidate_id not in (select id from candidate);")
    op.execute("delete from candidate_preferred_location where target_position_candidate_id not in (select id from candidate);")
    op.execute("delete from target_position where candidate_id not in (select id from candidate);")
    op.execute("ALTER TABLE candidate DROP CONSTRAINT target_position_candidate_id_fkey;")
    op.execute("ALTER TABLE target_position ADD CONSTRAINT target_position_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES candidate (id);")


    op.execute("ALTER TABLE candidate_preferred_location drop constraint candidate_preferred_location_tp_candidate_id_fkey;")
    op.execute("ALTER TABLE candidate_preferred_location RENAME COLUMN target_position_candidate_id to candidate_id ;")
    op.execute("ALTER TABLE candidate_preferred_location ADD CONSTRAINT  candidate_preferred_location_candidate_id_fkey "
               "FOREIGN KEY (candidate_id) REFERENCES candidate (id);")


    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("insert into target_position (candidate_id, created, role_id, minimum_salary) "
               "select id, NOW(), (select min(id) from role), 40000 from candidate where id not in (select distinct candidate_id from target_position);")
    op.execute("ALTER TABLE target_position DROP CONSTRAINT target_position_candidate_id_fkey;")
    op.execute("ALTER TABLE candidate ADD CONSTRAINT target_position_candidate_id_fkey "
               "FOREIGN KEY (id) REFERENCES target_position (candidate_id);")


    op.execute("ALTER TABLE candidate_preferred_location drop constraint candidate_preferred_location_candidate_id_fkey;")
    op.execute("ALTER TABLE candidate_preferred_location RENAME COLUMN candidate_id  to target_position_candidate_id;")
    op.execute("ALTER TABLE candidate_preferred_location ADD CONSTRAINT candidate_preferred_location_tp_candidate_id_fkey "
               "FOREIGN KEY (target_position_candidate_id) REFERENCES target_position (candidate_id);")


    ### end Alembic commands ###
