"""user created fields

Revision ID: 579082b48be0
Revises: 51c3c89a18d6
Create Date: 2015-06-01 11:18:05.330993

"""

# revision identifiers, used by Alembic.
revision = '579082b48be0'
down_revision = '51c3c89a18d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('user_created', sa.Boolean(), nullable=True, server_default='0'))
    op.add_column('degree', sa.Column('user_created', sa.Boolean(), nullable=True, server_default='0'))
    op.add_column('role', sa.Column('user_created', sa.Boolean(), nullable=True, server_default='0'))
    op.add_column('skill', sa.Column('user_created', sa.Boolean(), nullable=True, server_default='0'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'user_created')
    op.drop_column('role', 'user_created')
    op.drop_column('degree', 'user_created')
    op.drop_column('course', 'user_created')
    ### end Alembic commands ###
